global:
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: 'mysql'
    params:
      auth_module: [client]
    scrape_interval: 5s
    static_configs:
      - targets: 
        - logs_db:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysql_exporter:9104

  - job_name: 'logs_app'
    params:
      auth_module: [client]
    scrape_interval: 5s
    static_configs:
      - targets: 
        - logs_app:3000
